"""Self-contained HTML reports (design 010).

Every report is a single file with inline CSS, hand-drawn inline SVG charts,
and no JavaScript — open it in any browser offline, mail it, attach it to a
ticket. Values are HTML-escaped (a report may carry real partner data).
Collapsing uses native ``<details>``; sorting is done by pre-ordering rows.
"""

from __future__ import annotations

from html import escape
from pathlib import Path
from typing import Any

from mapcheck.engine.results import InterchangeResult, RunResult, Status
from mapcheck.report.trends import Trends

_STATUS_ORDER = [Status.FAIL, Status.WARNING, Status.NOT_TESTED, Status.PASS]
_STATUS_SLUG = {
    Status.PASS: "pass", Status.FAIL: "fail",
    Status.WARNING: "warn", Status.NOT_TESTED: "nt",
}
_RESULT_SLUG = {"PASS": "pass", "FAIL": "fail", "WARNING": "warn", "NOT_TESTED": "nt"}

_CSS = """
:root { color-scheme: light; }
* { box-sizing: border-box; }
body { margin: 0; padding: 2rem; background: #f4f5f7; color: #1c2430;
  font: 15px/1.5 -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif; }
.wrap { max-width: 1080px; margin: 0 auto; }
h1 { font-size: 1.5rem; margin: 0 0 .25rem; }
h2 { font-size: 1.1rem; margin: 2rem 0 .75rem; border-bottom: 2px solid #e3e6ea;
  padding-bottom: .3rem; }
.sub { color: #5b6672; font-size: .9rem; margin: 0 0 1rem; }
.card { background: #fff; border: 1px solid #e3e6ea; border-radius: 10px;
  padding: 1rem 1.25rem; margin-bottom: 1rem; box-shadow: 0 1px 2px rgba(0,0,0,.04); }
.meta { display: grid; grid-template-columns: max-content 1fr; gap: .2rem 1rem;
  font-size: .9rem; }
.meta dt { color: #5b6672; } .meta dd { margin: 0; word-break: break-all; }
.badge { display: inline-block; padding: .15rem .6rem; border-radius: 999px;
  font-weight: 700; font-size: .8rem; letter-spacing: .02em; }
.badge.big { font-size: 1.1rem; padding: .3rem 1rem; }
.pass { background: #e4f5e9; color: #1f7a3d; }
.fail { background: #fde4e4; color: #b31f1f; }
.warn { background: #fdf0d8; color: #8a5b00; }
.nt   { background: #eceff2; color: #5b6672; }
.tiles { display: flex; flex-wrap: wrap; gap: .75rem; margin-bottom: 1rem; }
.tile { flex: 1 1 140px; background: #fff; border: 1px solid #e3e6ea;
  border-radius: 10px; padding: .8rem 1rem; }
.tile .n { font-size: 1.6rem; font-weight: 700; } .tile .l { color: #5b6672;
  font-size: .82rem; }
table { border-collapse: collapse; width: 100%; font-size: .87rem; }
th, td { text-align: left; padding: .4rem .55rem; border-bottom: 1px solid #eef0f3;
  vertical-align: top; }
th { background: #fafbfc; color: #414b57; position: sticky; top: 0; }
td.msg { color: #414b57; } code { background: #f0f2f5; padding: 0 .25rem;
  border-radius: 4px; }
tr.fail td:first-child { border-left: 3px solid #b31f1f; }
tr.warn td:first-child { border-left: 3px solid #d79a1e; }
.bar { display: flex; align-items: center; gap: .5rem; margin: .2rem 0; }
.bar .lab { flex: 0 0 200px; font-size: .84rem; } .bar .num { color: #5b6672;
  font-size: .82rem; }
details { margin-top: .5rem; } summary { cursor: pointer; font-weight: 600;
  color: #414b57; }
.foot { color: #8a94a0; font-size: .78rem; margin-top: 2rem; text-align: center; }
.spec-row { display: flex; align-items: center; gap: .75rem; padding: .5rem 0;
  border-bottom: 1px solid #eef0f3; }
.spec-row .name { flex: 1 1 auto; font-weight: 600; word-break: break-all; }
.spec-row .rate { flex: 0 0 70px; text-align: right; font-variant-numeric: tabular-nums; }
"""


def _page(title: str, body: str) -> str:
    return (
        "<!doctype html>\n<html lang=\"en\"><head><meta charset=\"utf-8\">"
        "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
        f"<title>{escape(title)}</title><style>{_CSS}</style></head>"
        f"<body><div class=\"wrap\">{body}"
        "<p class=\"foot\">Generated by EDI MapCheck</p></div></body></html>\n"
    )


def _cell(value: Any) -> str:
    return escape("" if value is None else str(value))


def _badge(text: str, slug: str, big: bool = False) -> str:
    cls = f"badge {slug}" + (" big" if big else "")
    return f'<span class="{cls}">{escape(text)}</span>'


def _bar_rows(items: list[tuple[str, int]]) -> str:
    if not items:
        return '<p class="sub">None.</p>'
    top = max(n for _, n in items) or 1
    rows = []
    for label, n in items:
        width = max(2, round(100 * n / top))
        rows.append(
            f'<div class="bar"><span class="lab">{escape(label)}</span>'
            f'<svg width="220" height="14" role="img">'
            f'<rect width="{width * 2.2:.0f}" height="14" rx="3" fill="#4a72c4"></rect>'
            f'</svg><span class="num">{n}</span></div>'
        )
    return "".join(rows)


def _sparkline(series: list[str]) -> str:
    fill = {"PASS": "#2f9e52", "FAIL": "#d43b3b", "WARNING": "#d79a1e", "NOT_TESTED": "#aab2bd"}
    w, gap = 8, 2
    total = len(series) * (w + gap)
    rects = []
    for i, result in enumerate(series):
        x = i * (w + gap)
        rects.append(
            f'<rect x="{x}" y="0" width="{w}" height="16" rx="2" '
            f'fill="{fill.get(result, "#aab2bd")}"></rect>'
        )
    return f'<svg width="{total}" height="16" role="img">{"".join(rects)}</svg>'


def _findings_table(findings: list) -> str:
    head = (
        "<tr><th>Status</th><th>Row</th><th>Source</th><th>Target</th>"
        "<th>Expected</th><th>Actual</th><th>Category</th><th>Message</th></tr>"
    )
    rows = []
    for f in findings:
        slug = _STATUS_SLUG[f.status]
        rows.append(
            f'<tr class="{slug}"><td>{_badge(f.status.value, slug)}</td>'
            f"<td>{_cell(f.row_id)}</td><td>{_cell(f.source_ref)}</td>"
            f"<td>{_cell(f.target)}</td><td>{_cell(f.expected)}</td>"
            f"<td>{_cell(f.actual)}</td>"
            f"<td>{_cell(f.category.value if f.category else '')}</td>"
            f'<td class="msg">{_cell(f.message)}</td></tr>'
        )
    return f"<table>{head}{''.join(rows)}</table>"


def _counts_and_causes(result: RunResult | InterchangeResult) -> str:
    counts = result.counts
    count_items = [(s.value, counts[s]) for s in _STATUS_ORDER if counts[s]]
    causes = [(c.value, n) for c, n in result.category_counts.items()]
    return (
        '<div class="card"><h2 style="margin-top:0;border:0">Summary</h2>'
        '<div style="display:flex;gap:2rem;flex-wrap:wrap">'
        f'<div style="flex:1 1 260px"><strong>Status counts</strong>{_bar_rows(count_items)}</div>'
        f'<div style="flex:1 1 260px"><strong>Root causes</strong>{_bar_rows(causes)}</div>'
        "</div></div>"
    )


def _header(result: RunResult, overall: Status) -> str:
    slug = _STATUS_SLUG[overall]
    txn = f"{result.transaction_set or ''} {result.transaction_name or ''}".strip()
    return (
        f'<div class="card"><h1>EDI MapCheck report {_badge(overall.value, slug, big=True)}</h1>'
        f'<p class="sub">{escape(result.spec_name or "")}</p>'
        '<dl class="meta">'
        f"<dt>Transaction</dt><dd>{_cell(txn)}</dd>"
        f"<dt>Run at (UTC)</dt><dd>{_cell(result.run_at.strftime('%Y-%m-%d %H:%M:%S'))}</dd>"
        f"<dt>Spec</dt><dd>{_cell(result.spec_path)}</dd>"
        f"<dt>Source</dt><dd>{_cell(result.source_path)}</dd>"
        f"<dt>Output</dt><dd>{_cell(result.output_path)}</dd>"
        "</dl></div>"
    )


def _split_findings(findings: list) -> str:
    """Non-PASS table shown; PASS rows collapsed behind <details>."""
    ordered = sorted(findings, key=lambda f: f.sort_key)
    problems = [f for f in ordered if f.status is not Status.PASS]
    passes = [f for f in ordered if f.status is Status.PASS]
    out = []
    if problems:
        out.append(f'<div class="card">{_findings_table(problems)}</div>')
    else:
        out.append('<div class="card"><p class="sub">No problems — all checks passed.</p></div>')
    if passes:
        out.append(
            f'<details><summary>{len(passes)} passing check(s)</summary>'
            f'<div class="card">{_findings_table(passes)}</div></details>'
        )
    return "".join(out)


def render_run_html(result: RunResult) -> str:
    body = (
        _header(result, result.overall)
        + _counts_and_causes(result)
        + "<h2>Findings</h2>"
        + _split_findings(result.findings)
    )
    return _page(f"MapCheck — {result.spec_name or 'report'}", body)


def render_interchange_html(interchange: InterchangeResult) -> str:
    overall = interchange.overall
    slug = _STATUS_SLUG[overall]
    head = (
        f'<div class="card"><h1>EDI MapCheck interchange report '
        f'{_badge(overall.value, slug, big=True)}</h1>'
        f'<p class="sub">{escape(interchange.spec_name or "")} · '
        f'{len(interchange.documents)} document(s)</p>'
        '<dl class="meta">'
        f"<dt>Spec</dt><dd>{_cell(interchange.spec_path)}</dd>"
        f"<dt>Source</dt><dd>{_cell(interchange.source_path)}</dd>"
        f"<dt>Output</dt><dd>{_cell(interchange.output_path)}</dd>"
        "</dl></div>"
    )
    body = [head, _counts_and_causes(interchange)]
    if interchange.file_findings:
        body.append("<h2>File-level findings</h2>")
        body.append(f'<div class="card">{_findings_table(interchange.file_findings)}</div>')
    body.append("<h2>Documents</h2>")
    for doc in interchange.documents:
        r = doc.result
        dslug = _STATUS_SLUG[r.overall]
        body.append(
            f'<details><summary>{escape(doc.key)} {_badge(r.overall.value, dslug)}</summary>'
            f"{_split_findings(r.findings)}</details>"
        )
    return _page(f"MapCheck interchange — {interchange.spec_name or 'report'}", "".join(body))


def render_trends_html(trends: Trends) -> str:
    if trends.is_empty:
        return _page("MapCheck trends", '<div class="card"><h1>MapCheck trends</h1>'
                     '<p class="sub">No runs recorded yet.</p></div>')
    tiles = (
        '<div class="tiles">'
        f'<div class="tile"><div class="n">{trends.total_runs}</div>'
        '<div class="l">runs</div></div>'
        f'<div class="tile"><div class="n">{trends.overall_pass_rate:.0%}</div>'
        '<div class="l">overall pass rate</div></div>'
        f'<div class="tile"><div class="n">{trends.distinct_specs}</div>'
        '<div class="l">specs tracked</div></div></div>'
    )
    spec_rows = []
    for s in trends.specs:
        slug = _RESULT_SLUG.get(s.latest, "nt")
        spec_rows.append(
            f'<div class="spec-row"><span class="name">{escape(s.spec)}</span>'
            f"{_sparkline(s.series())}"
            f'<span class="rate">{s.pass_rate:.0%}</span>'
            f"{_badge(s.latest, slug)}"
            f'<span class="num">{s.total} run(s)</span></div>'
        )
    causes = f'<div class="card"><h2 style="margin-top:0;border:0">Top root causes</h2>' \
             f'{_bar_rows(trends.top_categories)}</div>'
    body = (
        '<div class="card"><h1>EDI MapCheck — history trends</h1>'
        '<p class="sub">Pass rate per spec over recent runs.</p></div>'
        + tiles
        + f'<div class="card"><h2 style="margin-top:0;border:0">By spec</h2>{"".join(spec_rows)}</div>'
        + causes
    )
    return _page("MapCheck trends", body)


def export_html(result: RunResult | InterchangeResult, path: str | Path) -> Path:
    """Write a single-run (or interchange) HTML report."""
    path = Path(path)
    if isinstance(result, InterchangeResult):
        html = render_interchange_html(result)
    else:
        html = render_run_html(result)
    path.write_text(html, encoding="utf-8")
    return path


def export_trends_html(trends: Trends, path: str | Path) -> Path:
    path = Path(path)
    path.write_text(render_trends_html(trends), encoding="utf-8")
    return path
